import { db } from "..";
import { ContinentInsert, continents } from "../schema/continents";
import { SymbolInsert, symbols } from "../schema/symbols";

async function main() {
  /** CONTINENTS **/
  const newContinents: ContinentInsert[] = [
    { id: "AF", name: "Africa" },
    { id: "AN", name: "Antarctica" },
    { id: "AS", name: "Asia" },
    { id: "EU", name: "Europe" },
    { id: "NA", name: "North America" },
    { id: "OC", name: "Oceania" },
    { id: "SA", name: "South America" },
    { id: "N/A", name: "No continent" },
  ];
  await db.insert(continents).values(newContinents);
  console.log(`${newContinents.length} continents created successfully!`);

  /** SYMBOLS **/
  const newSymbols: SymbolInsert[] = [
    { id: "AED", name: "United Arab Emirates Dirham", continentId: "AS" },
    { id: "AFN", name: "Afghan Afghani", continentId: "AS" },
    { id: "ALL", name: "Albanian Lek", continentId: "EU" },
    { id: "AMD", name: "Armenian Dram", continentId: "AS" },
    { id: "ANG", name: "Netherlands Antillean Guilder", continentId: "NA" },
    { id: "AOA", name: "Angolan Kwanza", continentId: "AF" },
    { id: "ARS", name: "Argentine Peso", continentId: "SA" },
    { id: "AUD", name: "Australian Dollar", continentId: "OC" },
    { id: "AWG", name: "Aruban Florin", continentId: "NA" },
    { id: "AZN", name: "Azerbaijani Manat", continentId: "AS" },
    {
      id: "BAM",
      name: "Bosnia-Herzegovina Convertible Mark",
      continentId: "EU",
    },
    { id: "BBD", name: "Barbadian Dollar", continentId: "NA" },
    { id: "BDT", name: "Bangladeshi Taka", continentId: "AS" },
    { id: "BGN", name: "Bulgarian Lev", continentId: "EU" },
    { id: "BHD", name: "Bahraini Dinar", continentId: "AS" },
    { id: "BIF", name: "Burundian Franc", continentId: "AF" },
    { id: "BMD", name: "Bermudan Dollar", continentId: "NA" },
    { id: "BND", name: "Brunei Dollar", continentId: "AS" },
    { id: "BOB", name: "Bolivian Boliviano", continentId: "SA" },
    { id: "BRL", name: "Brazilian Real", continentId: "SA" },
    { id: "BSD", name: "Bahamian Dollar", continentId: "NA" },
    { id: "BTC", name: "Bitcoin", continentId: "N/A" },
    { id: "BTN", name: "Bhutanese Ngultrum", continentId: "AS" },
    { id: "BWP", name: "Botswanan Pula", continentId: "AF" },
    { id: "BYN", name: "New Belarusian Ruble", continentId: "EU" },
    { id: "BYR", name: "Belarusian Ruble", continentId: "EU" },
    { id: "BZD", name: "Belize Dollar", continentId: "NA" },
    { id: "CAD", name: "Canadian Dollar", continentId: "NA" },
    { id: "CDF", name: "Congolese Franc", continentId: "AF" },
    { id: "CHF", name: "Swiss Franc", continentId: "EU" },
    { id: "CLF", name: "Chilean Unit of Account (UF)", continentId: "SA" },
    { id: "CLP", name: "Chilean Peso", continentId: "SA" },
    { id: "CNY", name: "Chinese Yuan", continentId: "AS" },
    { id: "CNH", name: "Chinese Yuan Offshore", continentId: "AS" },
    { id: "COP", name: "Colombian Peso", continentId: "SA" },
    { id: "CRC", name: "Costa Rican Colón", continentId: "NA" },
    { id: "CUC", name: "Cuban Convertible Peso", continentId: "NA" },
    { id: "CUP", name: "Cuban Peso", continentId: "NA" },
    { id: "CVE", name: "Cape Verdean Escudo", continentId: "AF" },
    { id: "CZK", name: "Czech Republic Koruna", continentId: "EU" },
    { id: "DJF", name: "Djiboutian Franc", continentId: "AF" },
    { id: "DKK", name: "Danish Krone", continentId: "EU" },
    { id: "DOP", name: "Dominican Peso", continentId: "NA" },
    { id: "DZD", name: "Algerian Dinar", continentId: "AF" },
    { id: "EGP", name: "Egyptian Pound", continentId: "AF" },
    { id: "ERN", name: "Eritrean Nakfa", continentId: "AF" },
    { id: "ETB", name: "Ethiopian Birr", continentId: "AF" },
    { id: "EUR", name: "Euro", continentId: "EU" },
    { id: "FJD", name: "Fijian Dollar", continentId: "OC" },
    { id: "FKP", name: "Falkland Islands Pound", continentId: "SA" },
    { id: "GBP", name: "British Pound Sterling", continentId: "EU" },
    { id: "GEL", name: "Georgian Lari", continentId: "AS" },
    { id: "GGP", name: "Guernsey Pound", continentId: "EU" },
    { id: "GHS", name: "Ghanaian Cedi", continentId: "AF" },
    { id: "GIP", name: "Gibraltar Pound", continentId: "EU" },
    { id: "GMD", name: "Gambian Dalasi", continentId: "AF" },
    { id: "GNF", name: "Guinean Franc", continentId: "AF" },
    { id: "GTQ", name: "Guatemalan Quetzal", continentId: "NA" },
    { id: "GYD", name: "Guyanaese Dollar", continentId: "SA" },
    { id: "HKD", name: "Hong Kong Dollar", continentId: "AS" },
    { id: "HNL", name: "Honduran Lempira", continentId: "NA" },
    { id: "HRK", name: "Croatian Kuna", continentId: "EU" },
    { id: "HTG", name: "Haitian Gourde", continentId: "NA" },
    { id: "HUF", name: "Hungarian Forint", continentId: "EU" },
    { id: "IDR", name: "Indonesian Rupiah", continentId: "AS" },
    { id: "ILS", name: "Israeli New Sheqel", continentId: "AS" },
    { id: "IMP", name: "Manx pound", continentId: "EU" },
    { id: "INR", name: "Indian Rupee", continentId: "AS" },
    { id: "IQD", name: "Iraqi Dinar", continentId: "AS" },
    { id: "IRR", name: "Iranian Rial", continentId: "AS" },
    { id: "ISK", name: "Icelandic Króna", continentId: "EU" },
    { id: "JEP", name: "Jersey Pound", continentId: "EU" },
    { id: "JMD", name: "Jamaican Dollar", continentId: "NA" },
    { id: "JOD", name: "Jordanian Dinar", continentId: "AS" },
    { id: "JPY", name: "Japanese Yen", continentId: "AS" },
    { id: "KES", name: "Kenyan Shilling", continentId: "AF" },
    { id: "KGS", name: "Kyrgystani Som", continentId: "AS" },
    { id: "KHR", name: "Cambodian Riel", continentId: "AS" },
    { id: "KMF", name: "Comorian Franc", continentId: "AF" },
    { id: "KPW", name: "North Korean Won", continentId: "AS" },
    { id: "KRW", name: "South Korean Won", continentId: "AS" },
    { id: "KWD", name: "Kuwaiti Dinar", continentId: "AS" },
    { id: "KYD", name: "Cayman Islands Dollar", continentId: "NA" },
    { id: "KZT", name: "Kazakhstani Tenge", continentId: "AS" },
    { id: "LAK", name: "Laotian Kip", continentId: "AS" },
    { id: "LBP", name: "Lebanese Pound", continentId: "AS" },
    { id: "LKR", name: "Sri Lankan Rupee", continentId: "AS" },
    { id: "LRD", name: "Liberian Dollar", continentId: "AF" },
    { id: "LSL", name: "Lesotho Loti", continentId: "AF" },
    { id: "LTL", name: "Lithuanian Litas", continentId: "EU" },
    { id: "LVL", name: "Latvian Lats", continentId: "EU" },
    { id: "LYD", name: "Libyan Dinar", continentId: "AF" },
    { id: "MAD", name: "Moroccan Dirham", continentId: "AF" },
    { id: "MDL", name: "Moldovan Leu", continentId: "EU" },
    { id: "MGA", name: "Malagasy Ariary", continentId: "AF" },
    { id: "MKD", name: "Macedonian Denar", continentId: "EU" },
    { id: "MMK", name: "Myanma Kyat", continentId: "AS" },
    { id: "MNT", name: "Mongolian Tugrik", continentId: "AS" },
    { id: "MOP", name: "Macanese Pataca", continentId: "AS" },
    { id: "MRU", name: "Mauritanian Ouguiya", continentId: "AF" },
    { id: "MUR", name: "Mauritian Rupee", continentId: "AF" },
    { id: "MVR", name: "Maldivian Rufiyaa", continentId: "AS" },
    { id: "MWK", name: "Malawian Kwacha", continentId: "AF" },
    { id: "MXN", name: "Mexican Peso", continentId: "NA" },
    { id: "MYR", name: "Malaysian Ringgit", continentId: "AS" },
    { id: "MZN", name: "Mozambican Metical", continentId: "AF" },
    { id: "NAD", name: "Namibian Dollar", continentId: "AF" },
    { id: "NGN", name: "Nigerian Naira", continentId: "AF" },
    { id: "NIO", name: "Nicaraguan Córdoba", continentId: "NA" },
    { id: "NOK", name: "Norwegian Krone", continentId: "EU" },
    { id: "NPR", name: "Nepalese Rupee", continentId: "AS" },
    { id: "NZD", name: "New Zealand Dollar", continentId: "OC" },
    { id: "OMR", name: "Omani Rial", continentId: "AS" },
    { id: "PAB", name: "Panamanian Balboa", continentId: "NA" },
    { id: "PEN", name: "Peruvian Nuevo Sol", continentId: "SA" },
    { id: "PGK", name: "Papua New Guinean Kina", continentId: "OC" },
    { id: "PHP", name: "Philippine Peso", continentId: "AS" },
    { id: "PKR", name: "Pakistani Rupee", continentId: "AS" },
    { id: "PLN", name: "Polish Zloty", continentId: "EU" },
    { id: "PYG", name: "Paraguayan Guarani", continentId: "SA" },
    { id: "QAR", name: "Qatari Rial", continentId: "AS" },
    { id: "RON", name: "Romanian Leu", continentId: "EU" },
    { id: "RSD", name: "Serbian Dinar", continentId: "EU" },
    { id: "RUB", name: "Russian Ruble", continentId: "EU" },
    { id: "RWF", name: "Rwandan Franc", continentId: "AF" },
    { id: "SAR", name: "Saudi Riyal", continentId: "AS" },
    { id: "SBD", name: "Solomon Islands Dollar", continentId: "OC" },
    { id: "SCR", name: "Seychellois Rupee", continentId: "AF" },
    { id: "SDG", name: "South Sudanese Pound", continentId: "AF" },
    { id: "SEK", name: "Swedish Krona", continentId: "EU" },
    { id: "SGD", name: "Singapore Dollar", continentId: "AS" },
    { id: "SHP", name: "Saint Helena Pound", continentId: "AF" },
    { id: "SLE", name: "Sierra Leonean Leone", continentId: "AF" },
    { id: "SLL", name: "Sierra Leonean Leone", continentId: "AF" },
    { id: "SOS", name: "Somali Shilling", continentId: "AF" },
    { id: "SRD", name: "Surinamese Dollar", continentId: "SA" },
    { id: "STD", name: "São Tomé and Príncipe Dobra", continentId: "AF" },
    { id: "SVC", name: "Salvadoran Colón", continentId: "NA" },
    { id: "SYP", name: "Syrian Pound", continentId: "AS" },
    { id: "SZL", name: "Swazi Lilangeni", continentId: "AF" },
    { id: "THB", name: "Thai Baht", continentId: "AS" },
    { id: "TJS", name: "Tajikistani Somoni", continentId: "AS" },
    { id: "TMT", name: "Turkmenistani Manat", continentId: "AS" },
    { id: "TND", name: "Tunisian Dinar", continentId: "AF" },
    { id: "TOP", name: "Tongan Paʻanga", continentId: "OC" },
    { id: "TRY", name: "Turkish Lira", continentId: "AS" },
    { id: "TTD", name: "Trinidad and Tobago Dollar", continentId: "NA" },
    { id: "TWD", name: "New Taiwan Dollar", continentId: "AS" },
    { id: "TZS", name: "Tanzanian Shilling", continentId: "AF" },
    { id: "UAH", name: "Ukrainian Hryvnia", continentId: "EU" },
    { id: "UGX", name: "Ugandan Shilling", continentId: "AF" },
    { id: "USD", name: "United States Dollar", continentId: "NA" },
    { id: "UYU", name: "Uruguayan Peso", continentId: "SA" },
    { id: "UZS", name: "Uzbekistan Som", continentId: "AS" },
    { id: "VEF", name: "Venezuelan Bolívar Fuerte", continentId: "SA" },
    { id: "VES", name: "Sovereign Bolivar", continentId: "SA" },
    { id: "VND", name: "Vietnamese Dong", continentId: "AS" },
    { id: "VUV", name: "Vanuatu Vatu", continentId: "OC" },
    { id: "WST", name: "Samoan Tala", continentId: "OC" },
    { id: "XAF", name: "CFA Franc BEAC", continentId: "AF" },
    { id: "XAG", name: "Silver (troy ounce)", continentId: "N/A" },
    { id: "XAU", name: "Gold (troy ounce)", continentId: "N/A" },
    { id: "XCD", name: "East Caribbean Dollar", continentId: "NA" },
    { id: "XDR", name: "Special Drawing Rights", continentId: "N/A" },
    { id: "XOF", name: "CFA Franc BCEAO", continentId: "AF" },
    { id: "XPF", name: "CFP Franc", continentId: "OC" },
    { id: "YER", name: "Yemeni Rial", continentId: "AS" },
    { id: "ZAR", name: "South African Rand", continentId: "AF" },
    { id: "ZMK", name: "Zambian Kwacha (pre-2013)", continentId: "AF" },
    { id: "ZMW", name: "Zambian Kwacha", continentId: "AF" },
    { id: "ZWL", name: "Zimbabwean Dollar", continentId: "AF" },
  ];
  await db.insert(symbols).values(newSymbols);
  console.log(`${newSymbols.length} symbols created successfully!`);
}

main();
